import { StyleSheet, Platform } from 'react-native';
import { colors } from '../../constants/colors';

export const modalLayoutStyles = StyleSheet.create({
  modal: {
    backgroundColor: colors.WHITE,
    width: '100%',
    borderRadius: 8,
    paddingTop: 8,
    paddingBottom: 32,
    paddingHorizontal: 20,
    alignSelf: 'center',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
    backgroundColor: 'rgba(255,255,255,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 8,
    fontSize: 18,
    color: colors.GRAY_60,
  },
  closeBtn: {
    alignSelf: 'flex-end',
    width: 16,
    height: 16,
    justifyContent: 'center',
    resizeMode: 'contain',
    marginRight: -8,
  },
  closeIcon: {
    width: 16,
    height: 16,
    tintColor: colors.GRAY_60,
  },
  headerRow: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 8,
  },
  title: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.GRAY_90,
  },
  vehicleInfo: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    columnGap: 8,
  },
  vehicleTag: {
    backgroundColor: colors.PRIMARY_10,
    color: colors.PRIMARY_50,
    fontSize: 18,
    fontWeight: '400',
    lineHeight: 28,
    borderRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  stepDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    columnGap: 10,
    marginVertical: 24,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.GRAY_15,
  },
  dotActive: { backgroundColor: colors.GRAY_80 },
  radioBtn: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioWrap: {},
  radioRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  radioBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.GRAY_10,
    borderRadius: 4,
    padding: 12,
    width: '49%',
    backgroundColor: colors.GRAY_05,
  },
  radioLabel: {
    fontSize: 17,
    color: colors.GRAY_80,
  },
  radioCircle: {
    width: 12,
    height: 12,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: colors.GRAY_50,
  },
  radioActive: {
    backgroundColor: colors.PRIMARY_50,
    borderColor: colors.PRIMARY_50,
  },
  amountInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  amountUnit: {
    fontSize: 20,
    color: colors.GRAY_60,
    marginLeft: 6,
    marginTop: Platform.OS === 'android' ? 2 : 0,
  },
  radioText: { fontSize: 20, color: colors.GRAY_90 },
  photoContainer: {
    width: '100%',
    borderWidth: 1,
    borderColor: colors.GRAY_10,
    borderRadius: 4,
    backgroundColor: colors.GRAY_05,
    padding: 16,
    marginBottom: 8,
  },
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    gap: 8,
  },
  photoItem: {
    borderRadius: 4,
    overflow: 'hidden',
    position: 'relative',
  },
  photoThumb: {
    width: '100%',
    height: '100%',
  },
  photoAddBtn: {
    borderWidth: 1,
    borderColor: colors.GRAY_20,
    borderRadius: 4,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addIconCircle: {
    padding: 8,
    borderRadius: 18,
    backgroundColor: colors.PRIMARY_50,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  addIcon: {
    width: 16,
    height: 16,
  },
  addText: {
    fontSize: 17,
    fontWeight: '400',
    color: colors.GRAY_50,
  },
  removeOverlay: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: colors.TRANSLUCENT,
    borderRadius: 10,
    padding: 2,
  },
  removeIcon: {
    width: 12,
    height: 12,
    tintColor: colors.WHITE,
  },
  subText: {
    color: colors.GRAY_50,
    fontSize: 17,
    fontWeight: '400',
    marginTop: 12,
    textAlign: 'center',
  },
  signatureBox: {
    alignItems: 'center',
    padding: 16,
    backgroundColor: colors.GRAY_05,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.GRAY_10,
  },
  subTitle: {
    fontSize: 17,
    color: colors.GRAY_50,
    fontWeight: '600',
    marginBottom: 12,
  },
  clearBtn: {
    alignSelf: 'center',
    marginTop: 12,
  },
  clearText: {
    fontSize: 17,
    color: colors.GRAY_50,
    fontWeight: '400',
  },
  signatureWrapper: {
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.GRAY_15,
    borderRadius: 8,
    overflow: 'hidden',
    width: '100%',
    aspectRatio: 2,
    backgroundColor: colors.WHITE,
    position: 'relative',
  },
  signaturePlaceholder: {
    position: 'absolute',
    top: '45%',
    left: 0,
    right: 0,
    textAlign: 'center',
    color: colors.GRAY_50,
    fontSize: 17,
    fontWeight: '400',
    zIndex: 1,
  },
  missingBox: {
    marginTop: 24,
    backgroundColor: colors.PRIMARY_00,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.PRIMARY_10,
    padding: 16,
    width: '100%',
  },
  missingTitle: {
    fontSize: 17,
    color: colors.GRAY_50,
    fontWeight: '400',
    marginBottom: 12,
  },
  missingList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
  },
  missingTag: {
    backgroundColor: colors.PRIMARY_10,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  missingTagText: {
    fontSize: 17,
    color: colors.PRIMARY_50,
    fontWeight: '400',
    lineHeight: 25,
  },
  footer: {
    marginTop: 24,
  },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerBtn: {
    flex: 1,
    alignItems: 'center',
    padding: 12,
    borderRadius: 4,
  },
  buttonContent: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  draftBtn: {
    borderWidth: 1,
    borderColor: colors.PRIMARY_50,
  },
  prevBtn: {
    flexDirection: 'row',
  },
  nextBtn: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  footerBtnText: {
    fontSize: 17,
    fontWeight: '400',
    lineHeight: 25,
    marginTop: Platform.OS === 'android' ? -1 : 0,
  },
  draftText: {
    color: colors.PRIMARY_50,
  },
  prevText: {
    color: colors.GRAY_90,
  },
  nextText: {
    color: colors.PRIMARY_50,
  },
  prevIcon: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    tintColor: colors.GRAY_90,
    marginRight: 4,
  },
  nextIcon: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    tintColor: colors.PRIMARY_50,
    marginLeft: 4,
  },
  sendBtn: {
    backgroundColor: colors.PRIMARY_50,
    borderRadius: 4,
    padding: 12,
    alignItems: 'center',
    marginBottom: 24,
  },
  sendBtnDisabled: { backgroundColor: colors.GRAY_15 },
  sendBtnText: {
    fontSize: 17,
    fontWeight: '400',
    color: colors.WHITE,
  },
});
